# Day 11: Exporting Data to JSON 
import json

print("--- Threat Intelligence Exporter ---")

# This is our Python dictionary (pretend this was generated by our Day 10 logic)
tracked_threats = {
  "192.168.1.50": 5,
  "10.0.0.5": 2,
  "8.8.8.8": 1,
  "45.33.22.11": 14 # High threat
}

export_filename = "threat_intel.json"

# We open the file in 'w' (write) mode
with open(export_filename, "w") as json_file:
  # json.dump() translates the Python dictionary into universal JSON format
  # indent=4 makes the file highly readable for us(humans)
  json.dump(tracked_threats, json_file, indent=4)

print(f"SUCCESS: Threat data successfully exported to {export_filename}")
